### ISSUE TITLE
API Feedback

### ISSUE THREAD

**Issue by mehaase** [ekampf/pymaybe#5]
I played around with `pymaybe` and I really like it! However there are a couple confusing things to a new user that might be improved. I hope you don't mind this constructive criticism. If you like these ideas, I'm happy to send a PR to implement them.

**Overriding `__str__` and `__repr__` is confusing.**

I played with `maybe` in the REPL and at first had no idea what was going on.

    >>> maybe(1)
    1
    >>> maybe([1,2,3])
    [1, 2, 3]

It looks like there is no wrapper, because `Maybe` is invoking `__str__` and `__repr__` on the wrapped object. Once you understand this, it might not seem problematic, but imagine you are debugging a complex program and you're printing out an object that is behaving strangely. When you print it out, it looks normal, and because the control flow is complex, you don't even realize that you're actually looking at a `Maybe` object.

Here's what I'd rather see:

    >>> maybe(1)
    Something(1)
    >>> maybe([1,2,3])
    Something([1, 2, 3])
    >>> maybe(None)
    Nothing

This would be better for the new user as well as the power user who is deep in the weeds debugging.

**Add an `or_none` or `unwrap` API.**

A common use case for me is to do work on an object if it is not `None`, otherwise evaluate to `None`. I can do this with the current API:

    >>> maybe(x).upper().zfill(10).or_else(None)
    >>> maybe(x).upper().zfill(10).or_else()

It's convenient that the default argument to `or_else` is `None`, but this makes for surprising code because "or else" sounds like it would need an argument. How about this instead?

    >>> maybe(x).upper().zfill(10).or_none() # synonym for or_else(None)

It also seems to me that `unwrap()` would be a good synonym for `or_else()`; this name is more explicit about what is happening (e.g. every `Maybe` needs to be unwrapped before you pass it to code that is not `Maybe` aware) and `unwrap(default=None)` is less confusing than `or_else(default=None)`.

**Custom exception for `get()`**

I'm not sure what purpose `get()` actually has, but it should raise a custom exception, e.g. `CannotGetNothing`, otherwise in a complex expression there is no simple way to detect when a call to `get()` has raised an exception.

    >>> try:
    ...   maybe(x).upper().zfill(10).get()
    ... except Exception:
    ...   pass

Imagine that `x` is an `int`: then this block will raise `AttributeError` because `int` does not have an `upper` attribute. This condition is indistinguishable from the condition that I actually want to trap. This would be better:

    >>> try:
    ...   maybe(x).upper().zfill(10).get()
    ... except CannotGetNothing:
    ...   pass

**Comment by ekampf** [comment]
hey @mehaase
thanks for the feedback!

1. I like your thoughts regarding `__str__` and `__repr__` though I want to double-check this isnt breaking any existing behavior before changing this.

2. You're absolutely correct regarding `or_none` and I'll add it to the library

3. `get` basically unwraps the optional value. In `Something` it'll return the unwrapped value, and in `Nothing` it'll raise an exception because there's no underlying value to return.
You are right that I should not be using the generic `Exception` class but type it or use one of the built in types (maybe `ValueError`?)

I'm currently on vacation out of the country but I just found how to make my flight productive :)
So you can expect a fix for these early next week...

**Comment by mehaase** [comment]
Well that's great, thank you! Let me know if I can help in any way. Testing or review or ... anything!

**Comment by ekampf** [comment]
@mehaase feel free to comment on the 3 new PRs :)

**Comment by mehaase** [comment]
I looked over the PR. It looks great.

**Comment by ekampf** [comment]
Will merge soon

**Comment by chrisdotcode** [comment]
ping @ekampf. Is this merge-ready as yet?

**Comment by rrauenza** [comment]
I think this PR is closeable is it not?

**Comment by rrauenza** [comment]
Love to see this merged and pushed ... I'm monkey patching my own or_none :)

Speaking of wich -- should or_none just be a @property?

**Comment by chrisdotcode** [comment]
Hi, @ekampf, it seems that this is all completed.

I'd love to be able to use this functionality now, so it possible that you could push it up to PyPI please? 🙂
